### PR TITLE
Fixes #51

### LINKED ISSUE #51: Session is being started if not started already
Hi,

I am actually testing around with zf2 session handling, e.g. and came to the point, where I created a lazy session manager since I dont want to start session stuff for any page if its not loaded.

I realized that SanSessionToolbar always creates a new Container instance (which triggers session start, e.g.) to fetch session data. 
This is kind of annoying since the session is probably not started since its not necessary at this moment.
Therefore sansessiontoolbar should display some kind of "session not started, no data available" or something like that instead of starting the whole session read/write stack e.g.

There are PHP functions to check if session is started, maybe you create a check in SanSession SessionManager like
```
 if (session_status() !== PHP_SESSION_ACTIVE) { return; } 
```

Until then, I have to disable this module for the moment. Probably I create a PR if I have some more time.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #51

### CODE REVIEW

**Comment by samsonasik** [comment]
there are still `Notice: Undefined variable: sessionData` error in tests, need works.

**Comment by samsonasik** [comment]
@boesing it should fixes #51, please tests by run:
```
composer require san/san-session-toolbar:dev-hotfix/51
```
in your project. Thanks!

**Comment by boesing** [comment]
You shouln't use "new SessionManager". Imho, using the static ```Container::getDefaultManager```is quite better. Anyways, your commits suits my needs and should be save for merging.

Thanks for that quick fix.

**Comment by samsonasik** [comment]
@boesing Thanks, I've updated with `Container::getDefaultManager()`, merging now ;).

**Comment by samsonasik** [comment]
merged. tagged 0.5.0 for it.

**Pull request merged**
