### PR TITLE
Update version laminas/laminas-dependency-plugin

### PR DESCRIPTION
**Pull request by dennybrandes**

### CODE REVIEW

**Comment by samsonasik** [comment]
actually, laminas dependency plugin is not required as it should already in skeleton, could you remove it?

**Comment by dennybrandes** [comment]
I removed it now

**Comment by dennybrandes** [comment]
If everything is ok, can you merge it and create a release for it? I need it in some project :-)

**Comment by samsonasik** [comment]
@dennybrandes merged and released 3.0.1 for it, Thank you ;)

**Comment by dennybrandes** [comment]
Great, thank you!

**Pull request merged**
